import {
	IconActivity,
	IconAlertCircle,
	IconAlertSquareRounded,
	IconAlertTriangle,
	IconArchive,
	IconArrowBadgeRight,
	IconArrowBadgeRightFilled,
	IconArrowLeft,
	IconArrowNarrowLeft,
	IconArrowNarrowRight,
	IconArrowRight,
	IconBackground,
	IconBarcode,
	IconAdjustments,
	IconBasketDollar,
	IconBell,
	IconBellBolt,
	IconBellCancel,
	IconBellCheck,
	IconBellCog,
	IconBellExclamation,
	IconBellFilled,
	IconBellHeart,
	IconBellMinus,
	IconBellOff,
	IconBellPlus,
	IconBellQuestion,
	IconBellRinging,
	IconBellRinging2Filled,
	IconBellSchool,
	IconBox,
	IconBoxModel2,
	IconBrandAppgallery,
	IconBrandGithub,
	IconBrandGoogle,
	IconBrandMedium,
	IconBrandMeta,
	IconBrandPatreon,
	IconBrandPatreonFilled,
	IconBrandTwitter,
	IconBrush,
	IconBug,
	IconBuilding,
	IconBuildingBank,
	IconBuildingStore,
	IconCalculator,
	IconCalendar,
	IconCalendarCheck,
	IconCalendarDollar,
	IconCalendarPlus,
	IconCalendarShare,
	IconCaretLeft,
	IconCaretLeftFilled,
	IconCaretRight,
	IconCaretRightFilled,
	IconCashRegister,
	IconChartArcs,
	IconChartArcs3,
	IconChartArea,
	IconChartAreaFilled,
	IconChartAreaLine,
	IconChartAreaLineFilled,
	IconChartArrows,
	IconChartArrowsVertical,
	IconChartBar,
	IconChartBarOff,
	IconChartBarPopular,
	IconChartBubble,
	IconChartBubbleFilled,
	IconChartCandle,
	IconChartCandleFilled,
	IconChartCircles,
	IconChartCohort,
	IconCheck,
	IconChevronDown,
	IconChevronLeft,
	IconChevronRight,
	IconCircle,
	IconCircleCheck,
	IconCircles,
	IconClearAll,
	IconClick,
	IconClipboardCopy,
	IconClipboardData,
	IconClock,
	IconCloudUpload,
	IconCodeDots,
	IconCoin,
	IconCommand,
	IconCopy,
	IconCreditCard,
	IconCurrencyDollar,
	IconDatabase,
	IconDeviceFloppy,
	IconDeviceLaptop,
	IconDeviceMobile,
	IconDirection,
	IconDirections,
	IconDots,
	IconDotsCircleHorizontal,
	IconDotsDiagonal,
	IconDotsDiagonal2,
	IconDotsVertical,
	IconDownload,
	IconEdit,
	IconEye,
	IconEyeClosed,
	IconFile,
	IconFileInvoice,
	IconFileText,
	IconFileTypePdf,
	IconFileTypeXls,
	IconFilter,
	IconFolder,
	IconGrid3x3,
	IconGrid4x4,
	IconGridDots,
	IconHash,
	IconHelpCircle,
	IconHistoryToggle,
	IconHome,
	IconId,
	IconInfoCircle,
	IconInfoSmall,
	IconKey,
	IconLabel,
	IconLabelFilled,
	IconLayersSelected,
	IconLayoutDashboard,
	IconLayoutKanban,
	IconLink,
	IconList,
	IconListDetails,
	IconLoader,
	IconLoader2,
	IconLocation,
	IconLock,
	IconLockAccess,
	IconLockOpen,
	IconLogin,
	IconLogout,
	IconLogout2,
	IconMail,
	IconMapPin,
	IconMinus,
	IconMoneybag,
	IconMoneybagMinus,
	IconMoneybagMove,
	IconMoneybagPlus,
	IconMoon,
	IconPackage,
	IconPencilMinus,
	IconPercentage,
	IconPhone,
	IconPhoto,
	IconPigMoney,
	IconPizza,
	IconPlayerTrackNext,
	IconPlus,
	IconPoint,
	IconPrinter,
	IconProgressCheck,
	IconProgressX,
	IconReceipt,
	IconReceiptDollar,
	IconRefresh,
	IconRocket,
	IconRosetteDiscountCheck,
	IconRosetteDiscountCheckFilled,
	IconRosetteDiscountCheckOff,
	IconRotate,
	IconRotate2,
	IconRotate360,
	IconRotate3d,
	IconRotateClockwise,
	IconSearch,
	IconServer,
	IconServerOff,
	IconSettings,
	IconSettingsCog,
	IconShare,
	IconShield,
	IconShieldLock,
	IconShoppingBag,
	IconShoppingBagHeart,
	IconShoppingCart,
	IconSlash,
	IconSortAscending,
	IconSortAscendingLetters,
	IconSortAZ,
	IconSortDescendingLetters,
	IconSparkles,
	IconSTurnDown,
	IconSun,
	IconTable,
	IconTag,
	IconTestPipe,
	IconTestPipe2,
	IconTicket,
	IconTrademark,
	IconTransform,
	IconTrash,
	IconTrendingDown,
	IconTrendingUp,
	IconTrophy,
	IconTruck,
	IconTruckLoading,
	IconUpload,
	IconUser,
	IconUserBitcoin,
	IconUserBolt,
	IconUserCancel,
	IconUserCheck,
	IconUserCircle,
	IconUserCode,
	IconUserCog,
	IconUserDollar,
	IconUserDown,
	IconUserEdit,
	IconUserExclamation,
	IconUserFilled,
	IconUserHeart,
	IconUserHexagon,
	IconUserOff,
	IconUserPause,
	IconUserPin,
	IconUserPlus,
	IconUserQuestion,
	IconUsers,
	IconUserSearch,
	IconUsersGroup,
	IconUserShield,
	IconUsersMinus,
	IconUserUp,
	IconUserX,
	IconWallet,
	IconX,
	IconZoom,
	IconListNumbers,
	IconCertificate,
	IconReceiptTax,
	IconArrowsSplit,
	IconSignature,
	IconSitemap,
	IconCopyright,
	IconGlobe,
	IconWorld,
	IconLanguage,
	IconMoodNeutral,
	IconFileTypeXml,
	IconBook,
	IconClipboardList,
	IconArrowsExchange,
	IconExternalLink,
	IconFileExport,
	IconMaximize,
	IconMinimize,
	IconHammer,
	IconStack,
	IconTruckDelivery,
	IconCodeAsterisk,
	IconClockX,
	IconStackForward,
	IconStack2,
	IconCategory,
	IconCategory2,
	IconRosette,
	IconDashboard,
	IconSmartHome,
	IconArrowsTransferUpDown,
	IconCircleX,
	IconAlertTriangleFilled,
	IconCircleXFilled,
	IconCircleCheckFilled,
	IconInfoCircleFilled,
	IconWifi,
	IconWifiOff,
	IconCamera,
	IconScan,
	IconSubtask,
	IconPackages,
	IconBellDollar,
	IconShoppingBagPlus,
	IconHistory,
	IconMoodDollar,
	IconBuildings,
	IconTransactionDollar,
	IconArrowsShuffle,
	IconArrowsJoin,
	IconPackageOff,
	IconBan,
	IconBoxModel2Off,
	IconCurrencyDollarOff,
	IconAlarm,
	IconArrowLeftCircle,
	IconArrowRightCircle,
	IconDeviceDesktop,
	IconBasket,
	IconClockCode,
	IconCode,
	IconMoneybagMoveBack,
	IconMilitaryRank,
} from '@tabler/icons-react'

export const Icons = {
	LayoutDashboard: IconLayoutDashboard,
	home: IconHome,
	wifi: IconWifi,
	alarm: IconAlarm,
	camera: IconCamera,
	subtask: IconSubtask,
	scan: IconScan,
	percentage: IconPercentage,
	wifiOff: IconWifiOff,
	smartHome: IconSmartHome,
	militaryRank: IconMilitaryRank,
	arrowsTransferUpDown: IconArrowsTransferUpDown,
	dashboard: IconDashboard,
	dataBase: IconDatabase,
	currencyDollarOff: IconCurrencyDollarOff,
	clockX: IconClockX,
	clockCode: IconClockCode,
	code: IconCode,
	maximize: IconMaximize,
	minimize: IconMinimize,
	fileExport: IconFileExport,
	shoppingBag: IconShoppingBag,
	shoppingBagPlus: IconShoppingBagPlus,
	wallet: IconWallet,
	stack: IconStack,
	stackForward: IconStackForward,
	stack2: IconStack2,
	category: IconCategory,
	category2: IconCategory2,
	rosette: IconRosette,
	lock: IconLock,
	lockOpen: IconLockOpen,
	book: IconBook,
	coin: IconCoin,
	externalLink: IconExternalLink,
	globe: IconGlobe,
	arrowsExchange: IconArrowsExchange,
	world: IconWorld,
	clipboardList: IconClipboardList,
	fileTypeXml: IconFileTypeXml,
	language: IconLanguage,
	directions: IconDirections,
	moon: IconMoon,
	playerTrackNext: IconPlayerTrackNext,
	cashRegister: IconCashRegister,
	share: IconShare,
	arrowLeftCircle: IconArrowLeftCircle,
	arrowRightCircle: IconArrowRightCircle,
	transform: IconTransform,
	ticket: IconTicket,
	basketDollar: IconBasketDollar,
	testPipe2: IconTestPipe2,
	history: IconHistory,
	moodDollar: IconMoodDollar,
	historyToggle: IconHistoryToggle,
	rocket: IconRocket,
	currencyDollar: IconCurrencyDollar,
	creditCard: IconCreditCard,
	deviceMobile: IconDeviceMobile,
	package: IconPackage,
	packageOff: IconPackageOff,
	packages: IconPackages,
	ban: IconBan,
	calculator: IconCalculator,
	sTurnDown: IconSTurnDown,
	brandMeta: IconBrandMeta,
	brandPatreon: IconBrandPatreon,
	arrowBadgeRight: IconArrowBadgeRight,
	arrowBadgeRightFilled: IconArrowBadgeRightFilled,
	label: IconLabel,
	labelFilled: IconLabelFilled,
	background: IconBackground,
	brandPatreonFilled: IconBrandPatreonFilled,
	printer: IconPrinter,
	clock: IconClock,
	activity: IconActivity,
	buildingBank: IconBuildingBank,
	fileText: IconFileText,
	mapPin: IconMapPin,
	progressX: IconProgressX,
	progressCheck: IconProgressCheck,
	barCode: IconBarcode,
	codeAsterisk: IconCodeAsterisk,
	sparkles: IconSparkles,
	trendingUp: IconTrendingUp,
	trendingDown: IconTrendingDown,
	moneyBag: IconMoneybag,
	moneybagMove: IconMoneybagMove,
	moneybagMoveBack: IconMoneybagMoveBack,
	moneybagMinus: IconMoneybagMinus,
	moneybagPlus: IconMoneybagPlus,
	pigMoney: IconPigMoney,
	phone: IconPhone,
	id: IconId,
	key: IconKey,
	shieldLock: IconShieldLock,
	lockAccess: IconLockAccess,
	link: IconLink,
	circles: IconCircles,
	fileTypePdf: IconFileTypePdf,
	fileTypeXls: IconFileTypeXls,
	file: IconFile,
	rosetteDiscountCheck: IconRosetteDiscountCheck,
	rosetteDiscountCheckFilled: IconRosetteDiscountCheckFilled,
	rosetteDiscountCheckOff: IconRosetteDiscountCheckOff,
	serverOff: IconServerOff,
	logo: IconCommand,
	truck: IconTruck,
	truckDelivery: IconTruckDelivery,
	shield: IconShield,
	infoSmall: IconInfoSmall,
	brandMedium: IconBrandMedium,
	grid4x4: IconGrid4x4,
	tag: IconTag,
	trademark: IconTrademark,
	grid3x3: IconGrid3x3,
	gridDots: IconGridDots,
	list: IconList,
	building: IconBuilding,
	hash: IconHash,
	store: IconBrandAppgallery,
	userDown: IconUserDown,
	userShield: IconUserShield,
	userUp: IconUserUp,
	server: IconServer,
	login: IconLogin,
	logout: IconLogout,
	logout2: IconLogout2,
	clearAll: IconClearAll,
	chevronDown: IconChevronDown,
	transactionDollar: IconTransactionDollar,
	arrowsShuffle: IconArrowsShuffle,
	arrowsJoin: IconArrowsJoin,
	close: IconX,
	shoppingBagHeart: IconShoppingBagHeart,
	buildingStore: IconBuildingStore,
	buildings: IconBuildings,
	spinnerSimple: IconLoader2,
	spinnerDecored: IconLoader,
	kanban: IconLayoutKanban,
	chevronLeft: IconChevronLeft,
	chevronRight: IconChevronRight,
	trash: IconTrash,
	truckLoading: IconTruckLoading,
	trophy: IconTrophy,
	employee: IconUserX,
	post: IconFileText,
	clipboardData: IconClipboardData,
	page: IconFile,
	userPen: IconUserEdit,
	user2: IconUserCircle,
	media: IconPhoto,
	copyright: IconCopyright,
	listNumbers: IconListNumbers,
	signature: IconSignature,
	certificate: IconCertificate,
	users: IconUser,
	IconSitemap: IconSitemap,
	receiptTax: IconReceiptTax,
	arrowsSplit: IconArrowsSplit,
	adjustments: IconAdjustments,
	settings: IconSettings,
	billing: IconCreditCard,
	ellipsis: IconDotsVertical,
	add: IconPlus,
	deviceLaptop: IconDeviceLaptop,
	basket: IconBasket,
	deviceDesktop: IconDeviceDesktop,
	warning: IconAlertTriangle,
	user: IconUser,
	iconArrowLeft: IconArrowLeft,
	arrowRight: IconArrowRight,
	caretRight: IconCaretRight,
	caretLeft: IconCaretLeft,
	caretRightFill: IconCaretRightFilled,
	caretLeftFill: IconCaretLeftFilled,
	arrowNarrowRight: IconArrowNarrowRight,
	arrowNarrowLeft: IconArrowNarrowLeft,
	help: IconHelpCircle,
	pizza: IconPizza,
	sun: IconSun,
	github: IconBrandGithub,
	twitter: IconBrandTwitter,
	check: IconCheck,
	brush: IconBrush,
	mail: IconMail,
	google: IconBrandGoogle,
	box: IconBox,
	boxModel2: IconBoxModel2,
	boxModel2Off: IconBoxModel2Off,
	eye: IconEye,
	eyeClosed: IconEyeClosed,
	cash: IconCreditCard,
	fileInvoice: IconFileInvoice,
	receipt: IconReceipt,
	inventory: IconBox,
	discount: IconArrowRight,
	customer: IconUserCircle,
	order: IconShoppingBag,
	table: IconTable,
	menu: IconFile,
	payment: IconCreditCard,
	refund: IconArrowRight,
	report: IconFileText,
	shoppingCart: IconShoppingCart,
	copy: IconCopy,
	layers: IconLayersSelected,
	folder: IconFolder,

	dotsVertical: IconDotsVertical,
	dots: IconDots,
	dotsCircleHorizontal: IconDotsCircleHorizontal,
	dotsDiagonal: IconDotsDiagonal,
	dotsDiagonal2: IconDotsDiagonal2,
	dodeDots: IconCodeDots,
	zoom: IconZoom,
	download: IconDownload,
	hammer: IconHammer,
	calendar: IconCalendar,
	calendarPlus: IconCalendarPlus,
	calendarDollar: IconCalendarDollar,
	calendarShare: IconCalendarShare,
	search: IconSearch,
	userSearch: IconUserSearch,
	moodNeutral: IconMoodNeutral,
	userQuestion: IconUserQuestion,
	click: IconClick,
	listDetails: IconListDetails,
	sortAZ: IconSortAZ,

	// TABLE
	rotate: IconRotate,
	rotate2: IconRotate2,
	rotate360: IconRotate360,
	rotate3d: IconRotate3d,
	rotateClockwise: IconRotateClockwise,
	edit: IconEdit,
	point: IconPoint,
	archive: IconArchive,
	photo: IconPhoto,
	pencilMinus: IconPencilMinus,
	plus: IconPlus,
	refresh: IconRefresh,
	x: IconX,
	sortAscending: IconSortAscending,
	sortAscendingLetters: IconSortAscendingLetters,
	sortDescendingLetters: IconSortDescendingLetters,
	alertSquareRounded: IconAlertSquareRounded,
	deviceFloppy: IconDeviceFloppy,
	filter: IconFilter,
	alertTriangle: IconAlertTriangle,
	alertTriangleFilled: IconAlertTriangleFilled,
	alertCircle: IconAlertCircle,

	// ALERT
	checkCircle: IconCircleCheck,
	checkCircleFilled: IconCircleCheckFilled,
	infoCircle: IconInfoCircle,
	infoCircleFilled: IconInfoCircleFilled,
	circleX: IconCircleX,
	circleXFilled: IconCircleXFilled,
	bug: IconBug,

	upload: IconUpload,
	cloudUpload: IconCloudUpload,
	minus: IconMinus,

	// CHARTS
	chartArcs: IconChartArcs,
	chartArcs3: IconChartArcs3,
	chartArea: IconChartArea,
	chartAreaFilled: IconChartAreaFilled,
	chartAreaLine: IconChartAreaLine,
	chartAreaLineFilled: IconChartAreaLineFilled,
	chartArrows: IconChartArrows,
	chartArrowsVertical: IconChartArrowsVertical,
	chartBar: IconChartBar,
	chartBarOff: IconChartBarOff,
	chartBarPopular: IconChartBarPopular,
	chartBubble: IconChartBubble,
	chartBubbleFilled: IconChartBubbleFilled,
	chartCandle: IconChartCandle,
	chartCandleFilled: IconChartCandleFilled,
	chartCircles: IconChartCircles,
	chartCohort: IconChartCohort,

	settingsCog: IconSettingsCog,
	slash: IconSlash,

	// Iconos de campana (bell)
	bell: IconBell, // Campana básica
	bellDollar: IconBellDollar, // Campana básica
	bellBolt: IconBellBolt, // Campana con rayo (notificaciones urgentes)
	bellRinging2Filled: IconBellRinging2Filled, // Campana sonando (relleno)
	bellOff: IconBellOff, // Campana desactivada
	bellPlus: IconBellPlus, // Campana con signo +
	bellMinus: IconBellMinus, // Campana con signo -
	bellQuestion: IconBellQuestion, // Campana con signo ?
	bellExclamation: IconBellExclamation, // Campana con signo !
	bellSchool: IconBellSchool, // Campana de escuela
	bellCancel: IconBellCancel, // Campana con símbolo de cancelación
	bellCheck: IconBellCheck, // Campana con marca de verificación
	bellHeart: IconBellHeart, // Campana con corazón
	bellRinging: IconBellRinging, // Campana sonando (otra variante)
	bellFilled: IconBellFilled, // Campana rellena
	bellCog: IconBellCog, // Campana con icono de configuración

	// USERS
	userX: IconUserX,
	userCog: IconUserCog,
	userOff: IconUserOff,
	userPin: IconUserPin,
	userUsers: IconUsers,
	userBolt: IconUserBolt,
	userEdit: IconUserEdit,
	userCode: IconUserCode,
	userPlus: IconUserPlus,
	userCheck: IconUserCheck,
	userHeart: IconUserHeart,
	userPause: IconUserPause,
	userGroup: IconUsersGroup,
	userMinus: IconUsersMinus,
	userFilled: IconUserFilled,
	userCircle: IconUserCircle,
	userCancel: IconUserCancel,
	userDollar: IconUserDollar,
	userBitcoin: IconUserBitcoin,
	userHexagon: IconUserHexagon,
	userExclamation: IconUserExclamation,
}
